version: '3'

services:
  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: meeguapi
    ports:
      - "3306:3306"

  app:
    build: .
    container_name: meeguapi-app
    ports:
      - 3000:3000
      - 5555:5555
    volumes:
      - .:/home/node/app
    command: >
      bash -c "npm install && npm run build && npm run start:dev"
    depends_on:
      - db
    user: "1000:1000"

volumes:
  db_data:
